version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/local/php-fpm/Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/app:cached
      - app-vendor-volume:/app/vendor
    working_dir: /app
  web:
    build:
      context: .
      dockerfile: ./docker/local/nginx/Dockerfile
    ports:
      - ${WEB_HTTP_PORT:-80}:80
    depends_on:
      - app
  db:
    build:
      context: .
      dockerfile: ./docker/local/mysql/Dockerfile
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker/local/mysql/logs:/var/log/mysql:delegated

volumes:
  app-vendor-volume:
  db-volume: